#----------------------------------------------------------#
#
#
#                        _brand
#
#      Generate theme/presentation_components.scss
#         — slide-card, panel, strip, blockquote,
#           and inline-text component styles for
#           Biostatistics RevealJS presentations
#
#        Canonical source — lecture repos download
#        this file from _brand at render time.
#
#                       O. Mottl
#                         2026
#
#----------------------------------------------------------#

generate_presentation_components <- function(
  output_file = here::here("theme/presentation_components.scss")
) {
  message("Generating theme/presentation_components.scss...\n")

  lines <- c(
    "// This file is auto-generated. Do not edit directly.",
    "// Run R/generate_theme.R to regenerate.",
    "",
    "@import \"colors\";",
    "",
    "/*-- scss:rules --*/",",
    "",
    "// ---------------------------------------------------------------------------",
    "// Slide spacing — after h2 and between sibling elements",
    "// ---------------------------------------------------------------------------",
    "",
    ".reveal .slides section:not(.center) > h2 {",
    "  margin-bottom: 0.58em;",
    "}",
    "",
    ".reveal .slides section:not(.center) > h2 + p,",
    ".reveal .slides section:not(.center) > h2 + .columns,",
    ".reveal .slides section:not(.center) > h2 + .cell,",
    ".reveal .slides section:not(.center) > h2 + .thought-box,",
    ".reveal .slides section:not(.center) > h2 + .blockquote,",
    ".reveal .slides section:not(.center) > h2 + .takeaway-strip {",
    "  margin-top: 0.55rem;",
    "}",
    "",
    ".reveal .slides section:not(.center) > p + .columns,",
    ".reveal .slides section:not(.center) > p + .cell,",
    ".reveal .slides section:not(.center) > p + .thought-box,",
    ".reveal .slides section:not(.center) > p + .blockquote,",
    ".reveal .slides section:not(.center) > p + .takeaway-strip {",
    "  margin-top: 1.2rem;",
    "}",
    "",
    ".reveal .slides section:not(.center) > .cell + .columns,",
    ".reveal .slides section:not(.center) > .cell + .blockquote,",
    ".reveal .slides section:not(.center) > .cell + .takeaway-strip,",
    ".reveal .slides section:not(.center) > .columns + .thought-box,",
    ".reveal .slides section:not(.center) > .columns + .takeaway-strip,",
    ".reveal .slides section:not(.center) > .blockquote + .takeaway-strip {",
    "  margin-top: 1.28rem;",
    "}",
    "",
    ".reveal .slides section:not(.center) > .cell + .takeaway-strip.compact-strip,",
    ".reveal .slides section:not(.center) > .columns + .takeaway-strip.compact-strip,",
    ".reveal .slides section:not(.center) > .blockquote + .takeaway-strip.compact-strip,",
    ".reveal .slides section:not(.center) > p + .takeaway-strip.compact-strip {",
    "  margin-top: 0.72rem;",
    "}",
    "",
    "// ---------------------------------------------------------------------------",
    "// Slide cards",
    "// ---------------------------------------------------------------------------",
    "",
    ".reveal .slide-card {",
    "  border-radius: 18px;",
    "  padding: 0.75rem 1rem 0.95rem 1rem;",
    "  box-shadow: 0 12px 28px rgba(0, 0, 0, 0.08);",
    "  text-align: left;",
    "  min-height: 10rem;",
    "  margin-bottom: 0.7rem;",
    "}",
    "",
    ".reveal .slide-card + .slide-card {",
    "  margin-top: 0.9rem;",
    "}",
    "",
    ".reveal .compact-card {",
    "  min-height: 8rem;",
    "}",
    "",
    ".reveal .slide-card h3 {",
    "  margin: 0 0 0.35rem 0;",
    "  color: $graphite;",
    "}",
    "",
    ".reveal .slide-card p,",
    ".reveal .slide-card ul {",
    "  font-size: 0.82em;",
    "  line-height: 1.35;",
    "}",
    "",
    ".reveal .slide-card ul {",
    "  margin-top: 0.35rem;",
    "}",
    "",
    "// ---------------------------------------------------------------------------",
    "// Kicker label",
    "// ---------------------------------------------------------------------------",
    "",
    "// display: block is required when using [text]{.kicker} Quarto inline syntax",
    "// (renders as <span> which is inline by default)",
    ".reveal .kicker {",
    "  display: block;",
    "  margin: 0 0 0.35rem 0;",
    "  font-size: 0.48em;",
    "  text-transform: uppercase;",
    "  letter-spacing: 0.08em;",
    "  font-weight: 700;",
    "  color: #6F6F6F;",
    "}",
    "",
    "// ---------------------------------------------------------------------------",
    "// Card colour variants",
    "// ---------------------------------------------------------------------------",
    "",
    ".reveal .vote-card {",
    "  background: #FFFAF1;",
    "  border-top: 7px solid $orange;",
    "}",
    "",
    ".reveal .checkpoint-known {",
    "  background: #F7F1FF;",
    "  border-top: 7px solid $indigo_velvet;",
    "}",
    "",
    ".reveal .checkpoint-open {",
    "  background: #FFF5DB;",
    "  border-top: 7px solid $orange;",
    "}",
    "",
    ".reveal .warning-card {",
    "  background: #FFF1F1;",
    "  border-top: 7px solid #C94C4C;",
    "}",
    "",
    ".reveal .rule-card {",
    "  background: #EEF6FF;",
    "  border-top: 7px solid #3A77B7;",
    "}",
    "",
    "// ---------------------------------------------------------------------------",
    "// Takeaway strip",
    "// ---------------------------------------------------------------------------",
    "",
    ".reveal .takeaway-strip {",
    "  margin-top: 0.8rem;",
    "  border-radius: 16px;",
    "  padding: 0.6rem 0.9rem;",
    "  text-align: left;",
    "  font-size: 0.8em;",
    "  background: linear-gradient(90deg, rgba(93, 40, 144, 0.12), rgba(243, 167, 18, 0.16));",
    "  border-left: 6px solid $indigo_velvet;",
    "}",
    "",
    ".reveal .takeaway-strip p {",
    "  margin: 0;",
    "}",
    "",
    "// ---------------------------------------------------------------------------",
    "// Inline text highlights",
    "// ---------------------------------------------------------------------------",
    "",
    ".reveal .answer-highlight {",
    "  color: $indigo_velvet;",
    "  font-weight: 700;",
    "}",
    "",
    ".reveal .warning-highlight {",
    "  color: #C94C4C;",
    "  font-weight: 700;",
    "}",
    "",
    ".reveal .soft-note {",
    "  font-size: 0.72em;",
    "  color: #6F6F6F;",
    "}",
    "",
    "// ---------------------------------------------------------------------------",
    "// Option / prompt / signal / open / warning panels",
    "// ---------------------------------------------------------------------------",
    "",
    ".reveal .option-panel,",
    ".reveal .prompt-panel,",
    ".reveal .signal-panel,",
    ".reveal .open-panel,",
    ".reveal .warning-panel {",
    "  padding: 0.65rem 0.9rem 0.8rem 0.9rem;",
    "  text-align: left;",
    "  border-radius: 12px;",
    "  min-height: 9.5rem;",
    "}",
    "",
    ".reveal .option-panel {",
    "  background: #FFFAF1;",
    "  border-left: 6px solid $orange;",
    "}",
    "",
    ".reveal .prompt-panel {",
    "  background: #F5F7FA;",
    "  border-left: 6px solid #7A8AA0;",
    "}",
    "",
    ".reveal .signal-panel {",
    "  background: #F7F1FF;",
    "  border-left: 6px solid $indigo_velvet;",
    "}",
    "",
    ".reveal .open-panel {",
    "  background: #FFF5DB;",
    "  border-left: 6px solid $orange;",
    "}",
    "",
    ".reveal .warning-panel {",
    "  background: #FFF1F1;",
    "  border-left: 6px solid #C94C4C;",
    "}",
    "",
    "// h3 and .panel-title headings inside panels share the same bottom margin",
    ".reveal .option-panel h3,",
    ".reveal .prompt-panel h3,",
    ".reveal .signal-panel h3,",
    ".reveal .open-panel h3,",
    ".reveal .warning-panel h3,",
    ".reveal .option-panel .panel-title,",
    ".reveal .prompt-panel .panel-title,",
    ".reveal .signal-panel .panel-title,",
    ".reveal .open-panel .panel-title,",
    ".reveal .warning-panel .panel-title {",
    "  margin: 0 0 0.35rem 0;",
    "}",
    "",
    "// .panel-title is used via [text]{.panel-title} Quarto inline syntax,",
    "// rendering as a <span>. display: block gives it heading-like layout.",
    "// No font-size — it inherits 0.82em from the panel p rule, matching",
    "// the original rendered size (the old 0.92em rule lost to the panel p",
    "// rule's higher cascade priority).",
    ".reveal .panel-title {",
    "  display: block;",
    "  font-weight: 700;",
    "}",
    "",
    "// Reset the wrapping <p> paragraph margin when it contains only a .panel-title",
    ".reveal .option-panel p:has(> .panel-title),",
    ".reveal .prompt-panel p:has(> .panel-title),",
    ".reveal .signal-panel p:has(> .panel-title),",
    ".reveal .open-panel p:has(> .panel-title),",
    ".reveal .warning-panel p:has(> .panel-title) {",
    "  margin: 0;",
    "}",
    "",
    "// .answer-title is used via [text]{.answer-title} Quarto inline syntax,",
    "// rendering as <p><span class=\"answer-title\">. Reset the wrapping <p>",
    "// font-size to 1em so the 1.38em on .answer-title applies from the slide",
    "// base font (not compounded with the panel's 0.82em p rule).",
    ".reveal .option-panel p:has(> .answer-title) {",
    "  font-size: 1em;",
    "  margin: 0;",
    "}",
    "",
    ".reveal .option-panel .answer-title {",
    "  display: block;",
    "  margin: 0 0 0.35rem 0;",
    "  font-size: 1.38em;",
    "  line-height: 1.08;",
    "  font-family: \"Source Sans 3\", \"Arial Narrow\", Arial, sans-serif;",
    "  font-weight: 600;",
    "  color: $indigo_velvet;",
    "  letter-spacing: -0.02em;",
    "}",
    "",
    "// ---------------------------------------------------------------------------",
    "// Column layout helpers",
    "// ---------------------------------------------------------------------------",
    "",
    ".reveal .columns.align-top {",
    "  align-items: flex-start;",
    "}",
    "",
    ".reveal .columns.align-top .cell,",
    ".reveal .columns.align-top p,",
    ".reveal .columns.align-top pre {",
    "  margin-top: 0;",
    "}",
    "",
    "// ---------------------------------------------------------------------------",
    "// Blockquote",
    "// ---------------------------------------------------------------------------",
    "",
    ".reveal .blockquote {",
    "  padding: 0.8rem 1rem;",
    "  border-radius: 0 12px 12px 0;",
    "  background: #F7F1FF;",
    "  border-left: 6px solid $indigo_velvet;",
    "  box-shadow: 0 8px 18px rgba(0, 0, 0, 0.06);",
    "  text-align: left;",
    "}",
    "",
    ".reveal .blockquote p {",
    "  margin: 0;",
    "}",
    "",
    ".reveal .blockquote ul {",
    "  margin: 0.35rem 0 0 1.15rem;",
    "}",
    "",
    ".reveal .blockquote p,",
    ".reveal .blockquote ul {",
    "  font-size: 0.82em;",
    "  line-height: 1.28;",
    "}",
    "",
    ".reveal .compact-blockquote {",
    "  margin-top: 0.3rem;",
    "  padding: 0.45rem 0.7rem;",
    "}",
    "",
    ".reveal .compact-blockquote p,",
    ".reveal .compact-blockquote ul {",
    "  font-size: 0.74em;",
    "  line-height: 1.22;",
    "}",
    "",
    "// ---------------------------------------------------------------------------",
    "// Compact strip (modifier on .takeaway-strip)",
    "// ---------------------------------------------------------------------------",
    "",
    ".reveal .compact-strip {",
    "  margin-top: 0.45rem;",
    "  padding: 0.45rem 0.75rem;",
    "  font-size: 0.72em;",
    "}",
    "",
    "// ---------------------------------------------------------------------------",
    "// Thought box",
    "// ---------------------------------------------------------------------------",
    "",
    ".reveal .thought-box {",
    "  margin-top: 0.55rem;",
    "  padding: 0.95rem 1.1rem;",
    "  border-radius: 16px;",
    "  background: #F7F1FF;",
    "  border-left: 8px solid $indigo_velvet;",
    "  text-align: left;",
    "  font-size: 0.95em;",
    "  line-height: 1.35;",
    "}",
    "",
    "// ---------------------------------------------------------------------------",
    "// Result panel",
    "// ---------------------------------------------------------------------------",
    "",
    ".reveal .result-panel {",
    "  margin-top: 0.35rem;",
    "  padding: 0.55rem 0.8rem;",
    "  border-radius: 12px;",
    "  background: #F8F9FA;",
    "  border-left: 6px solid #7A8AA0;",
    "  text-align: left;",
    "}",
    "",
    ".reveal .result-panel p {",
    "  margin: 0;",
    "}",
    "",
    ".reveal .result-panel code {",
    "  background: transparent;",
    "  font-size: 1em;",
    "}",
    "",
    "// ---------------------------------------------------------------------------",
    "// Panel text sizing — all panel types",
    "// ---------------------------------------------------------------------------",
    "",
    ".reveal .option-panel p,",
    ".reveal .option-panel ul,",
    ".reveal .prompt-panel p,",
    ".reveal .prompt-panel ul,",
    ".reveal .signal-panel p,",
    ".reveal .signal-panel ul,",
    ".reveal .open-panel p,",
    ".reveal .open-panel ul,",
    ".reveal .warning-panel p,",
    ".reveal .warning-panel ul {",
    "  font-size: 0.82em;",
    "  line-height: 1.35;",
    "}"
  )

  writeLines(lines, output_file)
  message("  Done: ", output_file, "\n")
}
